version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/homelab
    volumes:
      - app_data:/app
      - ./certs:/app/certs:ro
    depends_on:
      - mongo
    networks:
      - homelab_network

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - homelab_network

volumes:
  app_data:
  mongodb_data:

networks:
  homelab_network:
    driver: bridge
