version: '3.8'

services:
  app:
    build: .
    ports:
      - "8443:5000"  # Changed from 443:5000
      - "8080:5000"  # Changed from 80:5000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/homelab?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - homelab_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: >
      sh -c '
      /usr/local/bin/wait-for-it.sh mongo:27017 -t 60 &&
      npm start || { echo "App failed to start"; exit 1; }'
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/app/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking

  mongo:
    image: mongo:7.0
    command: ["mongod", "--auth", "--logpath", "/dev/null", "--quiet"]
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
    networks:
      - homelab_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: non-blocking
        env: "prod"
        env-regex: "^(MONGODB_|MONGO_)"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - homelab_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.3'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
    name: homelab_mongodb_data
  redis_data:
    name: homelab_redis_data

networks:
  homelab_network:
    driver: bridge